title: Orlando Companioni
logo: /Assets/img/ProfilePic.jpg
Email: companioniorlando@gmail.com
Location: Toronto, Canada
Phone: 647-648-9773
Linkedin: www.linkedin.com/in/orlando-companioni
show_downloads: false
theme: jekyll-theme-minimal
