title: Orlando Companioni
logo: /Assets/img/ProfilePic.jpg
Description: Email: companioniorlando@gmail.com\nLocation: Toronto, Canada\nPhone: 647-648-9773\nLinkedin: www.linkedin.com/in/orlando-companioni
show_downloads: false
theme: jekyll-theme-minimal
